# Generated by Django 3.1.1 on 2021-07-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, help_text='Пароль зашифрован, его можно только изменить', max_length=250, null=True, verbose_name='Пароль')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновления')),
            ],
            options={
                'verbose_name': 'Аутентификация в Мой Склад',
                'verbose_name_plural': 'Аутентификация в Мой Склад',
            },
        ),
    ]
