# Generated by Django 3.1.1 on 2021-07-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подключено'),
        ),
    ]
