# Generated by Django 3.1.1 on 2021-07-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0002_auto_20210728_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибки'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подключено'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Пароль'),
        ),
    ]
