# Generated by Django 3.1.1 on 2021-08-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0003_auto_20210729_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Лог'),
        ),
    ]
