# Generated by Django 4.2.5 on 2023-09-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0004_auto_20210809_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
