# Generated by Django 3.1.1 on 2021-12-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211126_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
