# Generated by Django 3.1.1 on 2021-12-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_fb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
