# Generated by Django 3.1.1 on 2020-09-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название продукта')),
                ('secondary_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='урл продукта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проудкта')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата поступления')),
                ('active', models.BooleanField(default=True, verbose_name='in trade')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
