# Generated by Django 3.1.1 on 2020-10-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название'),
        ),
    ]
