# Generated by Django 3.1.1 on 2020-10-01 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20201001_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('phone', models.CharField(max_length=25, null=True, verbose_name='Телефон')),
                ('reason', models.CharField(max_length=100, null=True, verbose_name='Тема')),
                ('another', models.TextField(max_length=25, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.AlterModelOptions(
            name='servicecallback',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
    ]
