# Generated by Django 3.1.1 on 2020-10-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20201001_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='another',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='callback',
            old_name='reason',
            new_name='topic',
        ),
    ]
