# Generated by Django 3.1.1 on 2020-10-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_popularsearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='servicecallback',
            options={'verbose_name': 'Форма заявки по сервису', 'verbose_name_plural': 'Форма заявки по сервисам'},
        ),
    ]
