# Generated by Django 3.1.1 on 2020-10-07 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20201005_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField(blank=True, null=True, verbose_name='Курс')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курс валют',
            },
        ),
    ]
