# Generated by Django 3.1.1 on 2020-10-09 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20201008_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_url', models.CharField(max_length=400, verbose_name='Урл для смс')),
                ('sms_login', models.CharField(max_length=400, verbose_name='Логин для смс')),
                ('sms_pwd', models.CharField(max_length=400, verbose_name='Пароль для смс')),
                ('sms_sender_id', models.CharField(max_length=400, verbose_name='Имя отправителя для смс')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
