# Generated by Django 3.1.1 on 2020-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='reserve_price',
            field=models.IntegerField(default=1000, verbose_name='Сумма залога'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('iphone', 'iPhone '), ('macBook', 'MacBook '), ('iPad', 'iPad'), ('iMac', 'iMac'), ('apple-watch', 'Apple Watch')], max_length=20, null=True, verbose_name='Категория'),
        ),
    ]
