# Generated by Django 3.1.1 on 2020-10-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_mainpage_mainpageproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='fifth_block_category',
            field=models.CharField(choices=[('iphone', 'iPhone '), ('macBook', 'MacBook '), ('iPad', 'iPad'), ('iMac', 'iMac'), ('apple-watch', 'Apple Watch'), ('gadgets', 'Гаджеты'), ('airpods', 'AirPods'), ('accessory', 'Акссесуары')], max_length=20, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='fifth_block_desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='fifth_block_link',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Сылка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='fifth_block_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название пятого блока'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='first_service_desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='first_service_img',
            field=models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='first_service_link',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Сылка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='first_service_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Первый сервис'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='main_product_desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='main_product_img',
            field=models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='main_product_img_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Мобильное изображение'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='main_product_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название главного продукта'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='news_desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='news_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название новостей'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='sale_product_desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='sale_product_img',
            field=models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='sale_product_img_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Мобильное изображение'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='sale_product_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название акционого продукт'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_product_desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_product_img',
            field=models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_product_img_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Мобильное изображение'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_product_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_service_desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_service_img',
            field=models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_service_link',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Сылка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_service_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Второй сервис'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='seventh_block_desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='seventh_block_link',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Сылка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='seventh_block_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название седьмого блока'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='sixth_block_category',
            field=models.CharField(choices=[('iphone', 'iPhone '), ('macBook', 'MacBook '), ('iPad', 'iPad'), ('iMac', 'iMac'), ('apple-watch', 'Apple Watch'), ('gadgets', 'Гаджеты'), ('airpods', 'AirPods'), ('accessory', 'Акссесуары')], max_length=20, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='sixth_block_desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='sixth_block_link',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Сылка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='sixth_block_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название шестого блока'),
        ),
    ]
