# Generated by Django 3.1.1 on 2020-10-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20201012_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='seventh_block_img',
            field=models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Изображение'),
        ),
    ]
