# Generated by Django 3.1.1 on 2020-10-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_mainpage_seventh_block_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_first',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Контактный номер'),
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_second',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Контактный номер 2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='schedule',
            field=models.CharField(default=100, max_length=400, verbose_name='Режим работы'),
            preserve_default=False,
        ),
    ]
