# Generated by Django 3.1.1 on 2020-10-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20201013_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='end_period',
            field=models.IntegerField(default=3, verbose_name='Срок до'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='start_period',
            field=models.IntegerField(default=12, verbose_name='Срок от'),
            preserve_default=False,
        ),
    ]
