# Generated by Django 3.1.1 on 2020-10-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20201014_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='desc_for_office',
            field=models.TextField(default=1, verbose_name='Оформление кредита в нашем офисе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='end_price',
            field=models.IntegerField(default=1, verbose_name='Сумма до'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='guarantor',
            field=models.BooleanField(default=False, verbose_name='Поручитель'),
        ),
        migrations.AddField(
            model_name='bank',
            name='initial_fee',
            field=models.IntegerField(default=1, verbose_name='Первоначальный взнос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='initial_fee_before',
            field=models.IntegerField(default=1, verbose_name='Первоначальный взнос до'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='repayment',
            field=models.CharField(default=1, max_length=400, verbose_name='Погашение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='start_price',
            field=models.IntegerField(default=1, verbose_name='Сумма от'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='term_of_consider',
            field=models.CharField(default=1, max_length=400, verbose_name='Сроки рассмотрения заявки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='desc',
            field=models.TextField(verbose_name='Необходимые документы'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='end_period',
            field=models.IntegerField(verbose_name='Сроки кредитования до'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='start_period',
            field=models.IntegerField(verbose_name='Сроки кредитования от'),
        ),
    ]
