# Generated by Django 3.1.1 on 2020-10-15 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201012_1429'),
        ('webapp', '0028_auto_20201014_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOnCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='ФИО')),
                ('phone', models.TextField(max_length=300, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('passport', models.CharField(blank=True, choices=[('1', 'ID паспорт'), ('2', 'Биометрический паспорт')], max_length=20, null=True, verbose_name='Пол')),
                ('passport_front', models.ImageField(upload_to='documents', verbose_name='Лицевая сторона паспорта')),
                ('passport_back', models.ImageField(upload_to='documents', verbose_name='Задняя сторона паспорта')),
                ('place_of_residence', models.ImageField(upload_to='documents', verbose_name='Справка с места жительства')),
                ('salary', models.CharField(blank=True, choices=[('1', 'ID паспорт'), ('2', 'Биометрический паспорт')], max_length=20, null=True, verbose_name='Справка о заработной плате')),
                ('salary_img', models.ImageField(upload_to='documents', verbose_name='Лицевая сторону паспорта')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Покупка в кредит',
                'verbose_name_plural': 'Покупки в кредит',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOnCreditProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=25, verbose_name='Ёмкость')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('month', models.CharField(max_length=100, verbose_name='Срок кредита')),
                ('per_month', models.CharField(max_length=100, verbose_name='Оплата в месяц')),
                ('price', models.CharField(max_length=100, verbose_name='Цена устройства на момент оформление')),
                ('price_converted', models.CharField(max_length=100, verbose_name='Цена устройства в сомах')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='webapp.purchaseoncredit')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_product', to='products.product')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
