# Generated by Django 3.1.1 on 2020-10-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_purchaseoncredit_purchaseoncreditproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseoncreditproducts',
            old_name='product',
            new_name='credit_product',
        ),
    ]
