# Generated by Django 3.1.1 on 2020-10-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_auto_20201015_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoncreditproducts',
            name='bank',
            field=models.CharField(default=1, max_length=200, verbose_name='Банк'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseoncredit',
            name='salary_img',
            field=models.ImageField(upload_to='documents', verbose_name='Справка о заработной плате файл'),
        ),
    ]
