# Generated by Django 3.1.1 on 2020-10-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_auto_20201016_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoncredit',
            name='passport',
            field=models.CharField(blank=True, choices=[('1', 'ID паспорт'), ('2', 'Биометрический паспорт')], max_length=20, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='purchaseoncredit',
            name='place_of_residence',
            field=models.ImageField(blank=True, null=True, upload_to='documents', verbose_name='Справка с места жительства'),
        ),
    ]
