# Generated by Django 3.1.1 on 2020-10-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_auto_20201016_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='agreement',
            field=models.TextField(default=1, verbose_name='Пользовательское соглашение'),
            preserve_default=False,
        ),
    ]
