# Generated by Django 3.1.1 on 2020-10-19 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201012_1429'),
        ('webapp', '0034_bank_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoncreditproducts',
            name='per_month',
            field=models.FloatField(verbose_name='Оплата в месяц'),
        ),
        migrations.AlterField(
            model_name='purchaseoncreditproducts',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена устройства на момент оформление'),
        ),
        migrations.AlterField(
            model_name='purchaseoncreditproducts',
            name='price_converted',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена устройства в сомах'),
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=200, verbose_name='Контактный номер')),
                ('capacity', models.CharField(max_length=25, verbose_name='Ёмкость')),
                ('payment', models.FloatField(max_length=100, verbose_name='Сумма брони')),
                ('price', models.FloatField(verbose_name='Цена устройства на момент брони')),
                ('price_converted', models.FloatField(verbose_name='Цена устройства в сомах')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve', to='products.product')),
            ],
            options={
                'verbose_name': 'Брони',
                'verbose_name_plural': 'Бронь',
            },
        ),
    ]
