# Generated by Django 3.1.1 on 2020-10-19 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_auto_20201019_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='color',
            field=models.CharField(default=1, max_length=25, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.date(2020, 10, 29), verbose_name='Дата конца брони'),
        ),
    ]
