# Generated by Django 3.1.1 on 2020-10-20 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_auto_20201019_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='transaction_id',
            field=models.CharField(default=1, max_length=200, verbose_name='Номер транзакции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.date(2020, 10, 30), verbose_name='Дата конца брони'),
        ),
    ]
