# Generated by Django 3.1.1 on 2020-10-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_auto_20201020_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reserve_price',
            field=models.FloatField(default=1, verbose_name='Цена брони'),
            preserve_default=False,
        ),
    ]
