# Generated by Django 3.1.1 on 2020-10-21 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20201021_1804'),
        ('webapp', '0039_auto_20201020_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 18, 4, 34, 364805), verbose_name='Дата конца брони'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, verbose_name='Номер транзакции')),
                ('to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Для оплаты в')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='products.order')),
                ('reserve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve', to='webapp.reserve')),
            ],
            options={
                'verbose_name': 'Брони',
                'verbose_name_plural': 'Бронь',
            },
        ),
    ]
