# Generated by Django 3.1.1 on 2020-10-21 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_auto_20201021_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 18, 11, 42, 859129), verbose_name='Дата конца брони'),
        ),
    ]
