# Generated by Django 3.1.1 on 2020-10-21 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_auto_20201021_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 18, 19, 34, 328318), verbose_name='Дата конца брони'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='payment',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма брони'),
        ),
    ]
