# Generated by Django 3.1.1 on 2020-10-21 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_auto_20201021_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 6, 8, 539413), verbose_name='Дата конца брони'),
        ),
    ]
