# Generated by Django 3.1.1 on 2020-10-21 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_auto_20201021_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='purchase',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 14, 41, 589651), verbose_name='Дата конца брони'),
        ),
    ]
