# Generated by Django 3.1.1 on 2020-10-30 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0049_auto_20201030_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.CharField(default=1, max_length=400, verbose_name='Описание сайта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title',
            field=models.CharField(default=1, max_length=400, verbose_name='Название сайта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 15, 48, 21, 686517), verbose_name='Дата конца брони'),
        ),
    ]
