# Generated by Django 3.1.1 on 2020-10-30 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_auto_20201030_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 17, 55, 6, 329147), verbose_name='Дата конца брони'),
        ),
    ]
