# Generated by Django 3.1.1 on 2020-10-31 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0054_auto_20201031_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 12, 4, 48, 885438), verbose_name='Дата конца брони'),
        ),
    ]
