# Generated by Django 3.1.1 on 2020-11-02 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0055_auto_20201031_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 9, 29, 27, 196894), verbose_name='Дата конца брони'),
        ),
    ]
