# Generated by Django 3.1.1 on 2020-11-02 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0056_auto_20201102_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoncreditproducts',
            name='module',
            field=models.TextField(blank=True, null=True, verbose_name='Модули'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='module',
            field=models.TextField(blank=True, null=True, verbose_name='Модули'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 9, 32, 9, 99506), verbose_name='Дата конца брони'),
        ),
    ]
