# Generated by Django 3.1.1 on 2020-11-12 15:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0058_auto_20201110_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=600, null=True, verbose_name='Название главного продукта')),
                ('img', models.ImageField(blank=True, null=True, upload_to='about_us_page', verbose_name='Изображение')),
                ('first_title', models.CharField(blank=True, max_length=600, null=True, verbose_name='Заголовок первого блока')),
                ('first_desc', models.CharField(blank=True, max_length=600, null=True, verbose_name='Описание')),
                ('first_img', models.ImageField(blank=True, null=True, upload_to='about_us_page', verbose_name='Изображение')),
                ('second_title', models.CharField(blank=True, max_length=600, null=True, verbose_name='Заголовок второго блока')),
                ('second_desc', models.CharField(blank=True, max_length=600, null=True, verbose_name='Описание')),
                ('second_img', models.ImageField(blank=True, null=True, upload_to='about_us_page', verbose_name='Изображение')),
                ('third_title', models.CharField(blank=True, max_length=600, null=True, verbose_name='Заголовок третьего блока')),
                ('third_desc', models.CharField(blank=True, max_length=600, null=True, verbose_name='Описание')),
                ('third_img', models.ImageField(blank=True, null=True, upload_to='about_us_page', verbose_name='Изображение')),
                ('fourth_title', models.CharField(blank=True, max_length=600, null=True, verbose_name='Заголовок четвертого блока')),
                ('fourth_desc', models.CharField(blank=True, max_length=600, null=True, verbose_name='Описание')),
                ('fourth_img', models.ImageField(blank=True, null=True, upload_to='about_us_page', verbose_name='Изображение')),
                ('shirt_title', models.CharField(blank=True, max_length=600, null=True, verbose_name='Дополнительный заголовок')),
                ('shirt_desc', models.TextField(blank=True, null=True, verbose_name='Дополнительное описание')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Страница о нас',
                'verbose_name_plural': 'Страница о нас',
            },
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 15, 19, 26, 619913), verbose_name='Дата конца брони'),
        ),
    ]
