# Generated by Django 3.1.1 on 2020-11-12 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0059_auto_20201112_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='shirt_desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 15, 24, 47, 138481), verbose_name='Дата конца брони'),
        ),
    ]
