# Generated by Django 3.1.1 on 2020-11-27 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0062_auto_20201127_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 0, 36, 962849), verbose_name='Дата конца брони'),
        ),
    ]
