# Generated by Django 3.1.1 on 2020-11-27 17:59

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0064_auto_20201127_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageslider',
            name='background',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Бэкграунд'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 17, 59, 43, 912746), verbose_name='Дата конца брони'),
        ),
    ]
