# Generated by Django 3.1.1 on 2020-11-28 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0066_auto_20201127_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='accessory_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аксессуары название'),
        ),
        migrations.AddField(
            model_name='category',
            name='adapter_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Переходники название'),
        ),
        migrations.AddField(
            model_name='category',
            name='another_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Разное название'),
        ),
        migrations.AddField(
            model_name='category',
            name='cable_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кабели название'),
        ),
        migrations.AddField(
            model_name='category',
            name='camera_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Камеры название'),
        ),
        migrations.AddField(
            model_name='category',
            name='cases_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Чехлы название'),
        ),
        migrations.AddField(
            model_name='category',
            name='charge_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Зарядные Устройства название'),
        ),
        migrations.AddField(
            model_name='category',
            name='drone_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дроны название'),
        ),
        migrations.AddField(
            model_name='category',
            name='gadget_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гаджеты название'),
        ),
        migrations.AddField(
            model_name='category',
            name='garmin_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Garmin название'),
        ),
        migrations.AddField(
            model_name='category',
            name='ipad_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='iPad название'),
        ),
        migrations.AddField(
            model_name='category',
            name='iphone_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='iPhone название'),
        ),
        migrations.AddField(
            model_name='category',
            name='keyboard_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Клавиатуры и мышки название'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_12',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='MacBook Retina 12 изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_12_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MacBook Retina 12 название'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_13',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='MacBook Pro 13 изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_13_air',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='MacBook Air 13 изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_13_air_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MacBook Air 13 название'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_13_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MacBook Pro 13 название'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_16',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='MacBook Pro 16 изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_16_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MacBook Pro 16 название'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_mini',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Mac mini изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_mini_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mac mini название'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_pro',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Mac Pro изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_pro_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mac Pro название'),
        ),
        migrations.AddField(
            model_name='category',
            name='mac_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mac название'),
        ),
        migrations.AddField(
            model_name='category',
            name='protective_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Защитные стекла название'),
        ),
        migrations.AddField(
            model_name='category',
            name='speaker_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Колонки название'),
        ),
        migrations.AddField(
            model_name='category',
            name='stabilizer_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стабилизаторы название'),
        ),
        migrations.AddField(
            model_name='category',
            name='stylus_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стилусы название'),
        ),
        migrations.AddField(
            model_name='category',
            name='tablets_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Графические планшеты название'),
        ),
        migrations.AddField(
            model_name='category',
            name='trade_ipad_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trade - in iPad название'),
        ),
        migrations.AddField(
            model_name='category',
            name='trade_iphone_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trade - in iPhone название'),
        ),
        migrations.AddField(
            model_name='category',
            name='trade_mac_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trade - in MacBook название'),
        ),
        migrations.AddField(
            model_name='category',
            name='trade_watch_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trade - in Apple Watch название'),
        ),
        migrations.AddField(
            model_name='category',
            name='tv_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Приставки название'),
        ),
        migrations.AddField(
            model_name='category',
            name='vr_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VR очки название'),
        ),
        migrations.AddField(
            model_name='category',
            name='watch_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Watch название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='charge',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Зарядные Устройства изображение'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 12, 5, 41, 310852), verbose_name='Дата конца брони'),
        ),
    ]
