# Generated by Django 3.1.1 on 2020-11-30 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0071_auto_20201128_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='custom_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Кастомный Курс'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 11, 53, 22, 933889), verbose_name='Дата конца брони'),
        ),
    ]
