# Generated by Django 3.1.1 on 2020-11-30 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0072_auto_20201130_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='time',
            field=models.TimeField(default='00:30', verbose_name='Промежуток обновление'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 12, 59, 42, 844309), verbose_name='Дата конца брони'),
        ),
    ]
