# Generated by Django 3.1.1 on 2020-11-30 13:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0073_auto_20201130_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 13, 0, 51, 745074), verbose_name='Дата конца брони'),
        ),
    ]
