# Generated by Django 3.1.1 on 2020-12-10 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0074_auto_20201130_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP клиента'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 14, 36, 19, 846825), verbose_name='Дата конца брони'),
        ),
    ]
