# Generated by Django 3.1.1 on 2020-12-10 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0076_auto_20201210_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 16, 35, 39, 829549), verbose_name='Дата конца брони'),
        ),
    ]
