# Generated by Django 3.1.1 on 2020-12-15 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0077_auto_20201210_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 14, 15, 13, 883776), verbose_name='Дата конца брони'),
        ),
    ]
