# Generated by Django 3.1.1 on 2020-12-16 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0078_auto_20201215_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='trade_another',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Trade - in Разное изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='trade_another_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trade - in Разное название'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 12, 8, 52, 286446), verbose_name='Дата конца брони'),
        ),
    ]
