# Generated by Django 3.1.1 on 2020-12-18 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0079_auto_20201216_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='online',
            field=models.BooleanField(default=True, verbose_name='Онлайн'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 14, 56, 9, 317721), verbose_name='Дата конца брони'),
        ),
    ]
