# Generated by Django 3.1.1 on 2020-12-18 15:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0080_auto_20201218_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=600, null=True, verbose_name='Название')),
                ('title_2', models.CharField(blank=True, max_length=600, null=True, verbose_name='Название')),
                ('text_1', models.CharField(blank=True, max_length=600, null=True, verbose_name='Условия банка')),
                ('text_2', models.CharField(blank=True, max_length=600, null=True, verbose_name='Сумма')),
                ('text_3', models.CharField(blank=True, max_length=600, null=True, verbose_name='Поручитель')),
                ('text_4', models.CharField(blank=True, max_length=600, null=True, verbose_name='Первоначальный взнос')),
                ('text_5', models.CharField(blank=True, max_length=600, null=True, verbose_name='Сроки кредитования')),
                ('text_6', models.CharField(blank=True, max_length=600, null=True, verbose_name='Сроки рассмотрения заявки')),
                ('text_7', models.CharField(blank=True, max_length=600, null=True, verbose_name='Погашение')),
                ('text_8', models.CharField(blank=True, max_length=600, null=True, verbose_name='Рассчитать кредит')),
                ('text_9', models.CharField(blank=True, max_length=600, null=True, verbose_name='Цена устройство')),
                ('text_10', models.CharField(blank=True, max_length=600, null=True, verbose_name='Выбрать банк')),
                ('text_11', models.CharField(blank=True, max_length=600, null=True, verbose_name='Срок')),
                ('text_12', models.CharField(blank=True, max_length=600, null=True, verbose_name='Процент')),
                ('text_13', models.CharField(blank=True, max_length=600, null=True, verbose_name='Первоначальный взнос')),
                ('text_14', models.CharField(blank=True, max_length=600, null=True, verbose_name='Результаты расчета')),
                ('text_15', models.CharField(blank=True, max_length=600, null=True, verbose_name='Сумма кредита:')),
                ('text_16', models.CharField(blank=True, max_length=600, null=True, verbose_name='Первоначальный взнос:')),
                ('text_17', models.CharField(blank=True, max_length=600, null=True, verbose_name='Срок кредита:')),
                ('text_18', models.CharField(blank=True, max_length=600, null=True, verbose_name='Ежемесячный платеж:')),
                ('text_19', models.CharField(blank=True, max_length=600, null=True, verbose_name='Ежемесячный платеж:')),
                ('text_20', models.CharField(blank=True, max_length=600, null=True, verbose_name='Общая выплата:')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Страница оформление в кредит',
                'verbose_name_plural': 'Страница оформление в кредит',
            },
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 15, 26, 48, 450626), verbose_name='Дата конца брони'),
        ),
    ]
