# Generated by Django 3.1.1 on 2020-12-18 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0081_auto_20201218_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpage',
            name='text_21',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Ежемесячный платеж:'),
        ),
        migrations.AddField(
            model_name='loanpage',
            name='text_22',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Общая выплата:'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_10',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Рассчитать кредит'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_11',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Цена устройство'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_12',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Выбрать банк'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_13',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_14',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_15',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Первоначальный взнос'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_16',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Результаты расчета'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_17',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Сумма кредита:'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_18',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Первоначальный взнос:'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_19',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Срок кредита:'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_20',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Ежемесячный платеж:'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_4',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Поручителья нет'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_5',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Поручителья есть'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_6',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Первоначальный взнос'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_7',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Сроки кредитования'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_8',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Сроки рассмотрения заявки'),
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_9',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Погашение'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 15, 31, 16, 254086), verbose_name='Дата конца брони'),
        ),
    ]
