# Generated by Django 3.1.1 on 2020-12-18 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0082_auto_20201218_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanpage',
            name='text_22',
        ),
        migrations.AlterField(
            model_name='loanpage',
            name='text_21',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Общая выплата:'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 15, 34, 40, 459680), verbose_name='Дата конца брони'),
        ),
    ]
