# Generated by Django 3.1.1 on 2020-12-23 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0086_auto_20201222_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='youtube',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Ссылка на YouTube'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 10, 41, 13, 679765), verbose_name='Дата конца брони'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название сайта'),
        ),
    ]
