# Generated by Django 3.1.1 on 2020-12-23 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0087_auto_20201223_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='percent2',
            field=models.FloatField(blank=True, null=True, verbose_name='2) Процент'),
        ),
        migrations.AddField(
            model_name='bank',
            name='percent3',
            field=models.FloatField(blank=True, null=True, verbose_name='3) Процент'),
        ),
        migrations.AddField(
            model_name='bank',
            name='percent4',
            field=models.FloatField(blank=True, null=True, verbose_name='4) Процент'),
        ),
        migrations.AddField(
            model_name='bank',
            name='percent5',
            field=models.FloatField(blank=True, null=True, verbose_name='5) Процент'),
        ),
        migrations.AddField(
            model_name='bank',
            name='percent6',
            field=models.FloatField(blank=True, null=True, verbose_name='6) Процент'),
        ),
        migrations.AddField(
            model_name='bank',
            name='percent_before',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент до достижение суммы'),
        ),
        migrations.AddField(
            model_name='bank',
            name='percent_before2',
            field=models.FloatField(blank=True, null=True, verbose_name='2) Процент до достижение суммы'),
        ),
        migrations.AddField(
            model_name='bank',
            name='percent_before3',
            field=models.FloatField(blank=True, null=True, verbose_name='3) Процент до достижение суммы'),
        ),
        migrations.AddField(
            model_name='bank',
            name='percent_before4',
            field=models.FloatField(blank=True, null=True, verbose_name='4) Процент до достижение суммы'),
        ),
        migrations.AddField(
            model_name='bank',
            name='percent_before5',
            field=models.FloatField(blank=True, null=True, verbose_name='5) Процент до достижение суммы'),
        ),
        migrations.AddField(
            model_name='bank',
            name='percent_before6',
            field=models.FloatField(blank=True, null=True, verbose_name='6) Процент до достижение суммы'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 15, 45, 23, 27516), verbose_name='Дата конца брони'),
        ),
    ]
