# Generated by Django 3.1.1 on 2020-12-23 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0089_auto_20201223_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpercents',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_percents', to='webapp.bank'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 16, 53, 35, 602969), verbose_name='Дата конца брони'),
        ),
    ]
