# Generated by Django 3.1.1 on 2020-12-24 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0092_auto_20201223_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradein',
            options={'verbose_name': 'Страница TradeIn', 'verbose_name_plural': 'Страница TradeIn'},
        ),
        migrations.AddField(
            model_name='loanpage',
            name='text_24',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Выберите опцию'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 11, 16, 35, 594669), verbose_name='Дата конца брони'),
        ),
    ]
