# Generated by Django 3.1.1 on 2020-12-26 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0096_auto_20201225_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='reserve_text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание залога'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 11, 35, 45, 658130), verbose_name='Дата конца брони'),
        ),
    ]
