# Generated by Django 3.1.1 on 2020-12-26 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0098_auto_20201226_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='seventh_block_img',
            field=models.FileField(blank=True, null=True, upload_to='main_page', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 12, 11, 39, 534889), verbose_name='Дата конца брони'),
        ),
    ]
