# Generated by Django 3.1.1 on 2021-03-11 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0099_auto_20201226_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoncredit',
            name='initial_fee',
            field=models.FloatField(blank=True, null=True, verbose_name='Первоначальный взнос'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 14, 28, 38, 215418), verbose_name='Дата конца брони'),
        ),
    ]
