# Generated by Django 3.1.1 on 2021-03-11 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0101_auto_20210311_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='accessory_1',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Доп. Акссесуары 1'),
        ),
        migrations.AddField(
            model_name='category',
            name='accessory_1_on',
            field=models.BooleanField(default=False, verbose_name='Доп. Акссесуары 1 включить'),
        ),
        migrations.AddField(
            model_name='category',
            name='accessory_1_title',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. Акссесуары 1 название'),
        ),
        migrations.AddField(
            model_name='category',
            name='accessory_2',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Доп. Акссесуары 2'),
        ),
        migrations.AddField(
            model_name='category',
            name='accessory_2_on',
            field=models.BooleanField(default=False, verbose_name='Доп. Акссесуары 2 включить'),
        ),
        migrations.AddField(
            model_name='category',
            name='accessory_2_title',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. Акссесуары 2 название'),
        ),
        migrations.AddField(
            model_name='category',
            name='accessory_3',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Доп. Акссесуары 3'),
        ),
        migrations.AddField(
            model_name='category',
            name='accessory_3_on',
            field=models.BooleanField(default=False, verbose_name='Доп. Акссесуары 3 включить'),
        ),
        migrations.AddField(
            model_name='category',
            name='accessory_3_title',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. Акссесуары 3 название'),
        ),
        migrations.AddField(
            model_name='category',
            name='gadget_1',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Доп. Гаджеты 1'),
        ),
        migrations.AddField(
            model_name='category',
            name='gadget_1_on',
            field=models.BooleanField(default=False, verbose_name='Доп. Гаджеты 1 включить'),
        ),
        migrations.AddField(
            model_name='category',
            name='gadget_1_title',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. Гаджеты 1 название'),
        ),
        migrations.AddField(
            model_name='category',
            name='gadget_2',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Доп. Гаджеты 2'),
        ),
        migrations.AddField(
            model_name='category',
            name='gadget_2_on',
            field=models.BooleanField(default=False, verbose_name='Доп. Гаджеты 2 включить'),
        ),
        migrations.AddField(
            model_name='category',
            name='gadget_2_title',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. Гаджеты 2 название'),
        ),
        migrations.AddField(
            model_name='category',
            name='gadget_3',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Доп. Гаджеты 3'),
        ),
        migrations.AddField(
            model_name='category',
            name='gadget_3_on',
            field=models.BooleanField(default=False, verbose_name='Доп. Гаджеты 3 включить'),
        ),
        migrations.AddField(
            model_name='category',
            name='gadget_3_title',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. Гаджеты 3 название'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 16, 20, 10, 126374), verbose_name='Дата конца брони'),
        ),
    ]
