# Generated by Django 3.1.1 on 2021-07-28 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0105_auto_20210728_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 22, 51, 4, 722824), verbose_name='Дата конца брони'),
        ),
    ]
