# Generated by Django 3.1.1 on 2021-07-29 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0109_auto_20210729_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 23, 4, 55, 205395), verbose_name='Дата конца брони'),
        ),
    ]
