# Generated by Django 3.1.1 on 2021-08-03 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0113_auto_20210729_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='custom_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибки'),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Синхронизировать'),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подключен'),
        ),
        migrations.AddField(
            model_name='currency',
            name='usd',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='USD id'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 22, 53, 0, 255025), verbose_name='Дата конца брони'),
        ),
    ]
