# Generated by Django 3.1.1 on 2021-08-03 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0114_auto_20210803_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Синхронизировать'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Подключен'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 22, 55, 19, 684957), verbose_name='Дата конца брони'),
        ),
    ]
