# Generated by Django 3.1.1 on 2021-08-09 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0115_auto_20210803_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 23, 13, 19, 452825), verbose_name='Дата конца брони'),
        ),
    ]
