# Generated by Django 3.1.1 on 2021-08-10 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0116_auto_20210809_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 10, 59, 53, 67675), verbose_name='Дата конца брони'),
        ),
    ]
