# Generated by Django 3.1.1 on 2021-08-12 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0117_auto_20210810_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 14, 12, 33, 706201), verbose_name='Дата конца брони'),
        ),
    ]
