# Generated by Django 3.1.1 on 2021-08-12 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0118_auto_20210812_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 14, 14, 28, 343860), verbose_name='Дата конца брони'),
        ),
    ]
