# Generated by Django 3.1.1 on 2021-09-19 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0120_auto_20210919_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 18, 18, 37, 601092), verbose_name='Дата конца брони'),
        ),
    ]
