# Generated by Django 3.1.1 on 2021-09-19 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0121_auto_20210919_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Статес'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 18, 21, 38, 564838), verbose_name='Дата конца брони'),
        ),
    ]
