# Generated by Django 3.1.1 on 2021-09-21 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0123_auto_20210919_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 23, 16, 3, 741607), verbose_name='Дата конца брони'),
        ),
    ]
