# Generated by Django 3.1.1 on 2021-09-25 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0127_auto_20210924_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 23, 48, 2, 26211), verbose_name='Дата конца брони'),
        ),
    ]
