# Generated by Django 3.1.1 on 2021-09-26 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0128_auto_20210925_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 0, 0, 19, 901609), verbose_name='Дата конца брони'),
        ),
    ]
