# Generated by Django 3.1.1 on 2021-09-26 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0129_auto_20210926_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageslider',
            name='description',
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='mainpageslider', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mainpageslider', verbose_name='Изображение для мобильных устройств'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 18, 45, 16, 615878), verbose_name='Дата конца брони'),
        ),
    ]
