# Generated by Django 3.1.1 on 2021-09-26 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0130_auto_20210926_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 18, 59, 7, 365269), verbose_name='Дата конца брони'),
        ),
    ]
