# Generated by Django 3.1.1 on 2021-09-26 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0131_auto_20210926_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageslider',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 18, 59, 18, 767569), verbose_name='Дата конца брони'),
        ),
    ]
