# Generated by Django 3.1.1 on 2021-09-26 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_auto_20210926_0000'),
        ('webapp', '0132_auto_20210926_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 19, 26, 56, 572206), verbose_name='Дата конца брони'),
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=600, null=True, verbose_name='Название')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
                ('products', models.ManyToManyField(to='products.Product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Сравнение',
                'verbose_name_plural': 'Сравнения',
            },
        ),
    ]
