# Generated by Django 3.1.1 on 2021-09-26 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0134_auto_20210926_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 22, 4, 58, 798023), verbose_name='Дата конца брони'),
        ),
    ]
