# Generated by Django 3.1.1 on 2021-10-03 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0135_auto_20210926_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='additionalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Изображение')),
                ('slug_name', models.TextField(blank=True, null=True, verbose_name='Ссылка')),
                ('main_category', models.CharField(choices=[('mac', 'Mac'), ('gadgets', 'Гаджеты '), ('accessory', 'Аксессуары')], max_length=120, null=True, verbose_name='Категория')),
                ('active', models.BooleanField(default=False, verbose_name='Включить')),
            ],
            options={
                'verbose_name': 'Доп Категории',
                'verbose_name_plural': 'Доп Категорий',
            },
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 15, 49, 44, 225016), verbose_name='Дата конца брони'),
        ),
    ]
