# Generated by Django 3.1.1 on 2021-10-03 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0137_auto_20211003_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalcategory',
            options={'verbose_name': 'Доп Категорий', 'verbose_name_plural': 'Доп Категории'},
        ),
        migrations.AlterField(
            model_name='additionalcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='additionalcategory',
            name='slug_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 15, 53, 29, 444790), verbose_name='Дата конца брони'),
        ),
    ]
