# Generated by Django 3.1.1 on 2021-10-03 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0138_auto_20211003_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 21, 57, 31, 915891), verbose_name='Дата конца брони'),
        ),
    ]
