# Generated by Django 3.1.1 on 2021-10-03 22:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_remove_orderproduct_module'),
        ('webapp', '0141_auto_20211003_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='module',
        ),
        migrations.AddField(
            model_name='reserve',
            name='caseSize',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер корпуса'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='connectivity',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Возможности подключения'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='cpu',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='edition',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Edition'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='keyboard',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Раскладка клавиатуры'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='pattern',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='ram',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_reserve', to='products.productspecification'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 22, 37, 14, 748855), verbose_name='Дата конца брони'),
        ),
    ]
