# Generated by Django 3.1.1 on 2021-10-03 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0142_auto_20211003_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 22, 45, 27, 21652), verbose_name='Дата конца брони'),
        ),
    ]
