# Generated by Django 3.1.1 on 2021-10-03 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0143_auto_20211003_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 23, 5, 2, 903659), verbose_name='Дата конца брони'),
        ),
    ]
