# Generated by Django 3.1.1 on 2021-10-03 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0150_auto_20211003_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='page_description',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 23, 48, 16, 260126), verbose_name='Дата конца брони'),
        ),
    ]
