# Generated by Django 3.1.1 on 2021-10-04 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0151_auto_20211003_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageslider',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='mainpageslider', verbose_name='Изображение для мобильных устройств'),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mainpageslider', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 15, 9, 46, 668330), verbose_name='Дата конца брони'),
        ),
    ]
