# Generated by Django 3.1.1 on 2021-10-12 22:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_auto_20211003_2307'),
        ('webapp', '0152_auto_20211004_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseoncreditproducts',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='purchaseoncreditproducts',
            name='color',
        ),
        migrations.AddField(
            model_name='purchaseoncreditproducts',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='products.productspecification'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 22, 51, 28, 13484), verbose_name='Дата конца брони'),
        ),
    ]
