# Generated by Django 3.1.1 on 2021-10-12 23:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_auto_20211003_2307'),
        ('webapp', '0153_auto_20211012_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseoncreditproducts',
            name='module',
        ),
        migrations.AlterField(
            model_name='purchaseoncreditproducts',
            name='credit_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_product', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='purchaseoncreditproducts',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='products.productspecification', verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 23, 7, 21, 529030), verbose_name='Дата конца брони'),
        ),
    ]
