# Generated by Django 3.1.1 on 2021-10-12 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0154_auto_20211012_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='main_product_desc',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='main_product_img',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='main_product_img_mobile',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='main_product_title',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='sale_product',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='sale_product_desc',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='sale_product_img',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='sale_product_img_mobile',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='sale_product_title',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 23, 18, 47, 218417), verbose_name='Дата конца брони'),
        ),
    ]
