# Generated by Django 3.1.1 on 2021-11-23 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0157_auto_20211123_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='bank',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='loanpage',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='tradein',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='whyus',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 16, 12, 44, 524119), verbose_name='Дата конца брони'),
        ),
    ]
