# Generated by Django 3.1.1 on 2021-11-23 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0158_auto_20211123_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 18, 38, 36, 888836), verbose_name='Дата конца брони'),
        ),
    ]
