# Generated by Django 3.1.1 on 2021-11-24 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0159_auto_20211123_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 11, 8, 8, 661401), verbose_name='Дата конца брони'),
        ),
    ]
