# Generated by Django 3.1.1 on 2021-11-30 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0163_auto_20211126_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 12, 0, 40, 817120), verbose_name='Дата конца брони'),
        ),
    ]
