# Generated by Django 3.1.1 on 2021-12-02 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0164_auto_20211130_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 17, 59, 5, 410386), verbose_name='Дата конца брони'),
        ),
    ]
