# Generated by Django 3.1.1 on 2021-12-24 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0166_auto_20211202_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 13, 13, 11, 482739), verbose_name='Дата конца брони'),
        ),
    ]
