# Generated by Django 3.1.1 on 2021-12-24 17:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0167_auto_20211224_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reserve', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 17, 28, 23, 554334), verbose_name='Дата конца брони'),
        ),
    ]
