<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-09-25 09:42
=======
# Generated by Django 4.2.5 on 2023-09-25 08:28
>>>>>>> 30af952fb5a12d90d44047f8e5b00922663100a8

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0170_alter_reserve_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 9, 42, 49, 555017), verbose_name='Дата конца брони'),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 14, 28, 18, 531203), verbose_name='Дата конца брони'),
>>>>>>> 30af952fb5a12d90d44047f8e5b00922663100a8
        ),
    ]
