# Generated by Django 4.2.5 on 2023-09-25 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0170_alter_reserve_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 9, 42, 49, 555017), verbose_name='Дата конца брони'),
        ),
    ]
