# Generated by Django 4.2 on 2023-09-26 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0172_alter_reserve_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 13, 38, 34, 93429), verbose_name='Дата конца брони'),
        ),
    ]
