# Generated by Django 3.1.1 on 2020-09-25 12:19

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='Ёмкость')),
                ('measure', models.CharField(choices=[('mb', 'MB'), ('gb', 'GB'), ('tb', 'TB')], max_length=20, null=True, verbose_name='Измерять в')),
            ],
            options={
                'verbose_name': 'ёмкость',
                'verbose_name_plural': 'Ёмкости',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название цвета')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=250, verbose_name='Название продукта')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='Описание проудкта')),
                ('slug_name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='урл продукта')),
                ('in_trade', models.BooleanField(default=False, verbose_name='in trade')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата поступления')),
                ('product_category', models.CharField(choices=[('iphone', 'iPhone '), ('mackBook', 'MacBook '), ('iPad', 'iPad'), ('iMac', 'iMac'), ('apple-watch', 'Apple Watch'), ('gadgets', 'Гаджеты'), ('accessory', 'Акссесуары')], max_length=20, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Колличество')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена за штуку в $')),
                ('capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_capacity', to='products.capacity', verbose_name='ёмкость')),
                ('color_hex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_hex', to='products.color', verbose_name='цвет')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='products.product')),
            ],
            options={
                'verbose_name': 'спецификацию',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Изображение')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.product')),
                ('product_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_color', to='products.color', verbose_name='цвет продукта')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Изображении',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug_name', models.CharField(blank=True, max_length=210, null=True, unique=True, verbose_name='урл категории')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Токен')),
                ('color', models.IntegerField(blank=True, null=True, verbose_name='Цвет')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Ёмкость')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Колличество')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата поступления')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product')),
            ],
        ),
    ]
