# Generated by Django 3.1.1 on 2020-09-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название промокода')),
                ('code_word', models.CharField(blank=True, max_length=210, null=True, unique=True, verbose_name='Кодовое слово')),
                ('percent', models.IntegerField(blank=True, null=True, verbose_name='Процент')),
                ('in_usd', models.IntegerField(blank=True, null=True, verbose_name='На сумму в $')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
