# Generated by Django 3.1.1 on 2020-09-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.IntegerField(blank=True, null=True, verbose_name='Рекомендует')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recommended', to='products.product')),
            ],
            options={
                'verbose_name': 'Рекомендуемый',
                'verbose_name_plural': 'Рекомендуемые',
            },
        ),
    ]
