# Generated by Django 3.1.1 on 2020-09-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommended', to='products.product'),
        ),
        migrations.AlterField(
            model_name='recommended',
            name='recommended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='products.product'),
        ),
    ]
