# Generated by Django 3.1.1 on 2020-09-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200928_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
