# Generated by Django 3.1.1 on 2020-09-30 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_basket_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField(blank=True, null=True, verbose_name='Цвет')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Ёмкость')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('converted', models.IntegerField(blank=True, null=True, verbose_name='Цена в сомах')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Колличество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата поступления')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_order_products', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
