# Generated by Django 3.1.1 on 2020-09-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка по промокоду'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_name',
            field=models.IntegerField(blank=True, null=True, verbose_name='Название промокода'),
        ),
    ]
