# Generated by Django 3.1.1 on 2020-09-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200930_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='in_usd',
        ),
    ]
