# Generated by Django 3.1.1 on 2020-09-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_promocode_in_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название промокода'),
        ),
    ]
