# Generated by Django 3.1.1 on 2020-10-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200930_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Свойство')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_spec', to='products.product')),
            ],
            options={
                'verbose_name': 'допольнительные свойство',
                'verbose_name_plural': 'допольнительные свойства',
            },
        ),
    ]
