# Generated by Django 3.1.1 on 2020-10-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='capacity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ёмкость'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цвет'),
        ),
    ]
