# Generated by Django 3.1.1 on 2020-10-08 11:45

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201008_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='color_hex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_hex', to='products.color', verbose_name='цвет'),
        ),
    ]
