# Generated by Django 3.1.1 on 2020-10-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201008_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='capacity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ёмкость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
    ]
