# Generated by Django 3.1.1 on 2020-10-21 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20201021_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='formalized',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='formalized',
            field=models.BooleanField(default=False, verbose_name='Оформлен'),
        ),
    ]
