# Generated by Django 3.1.1 on 2020-10-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20201021_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Способ доставки'),
        ),
    ]
