# Generated by Django 3.1.1 on 2020-10-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='need_pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
