# Generated by Django 3.1.1 on 2020-10-30 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата поступления'),
        ),
    ]
