# Generated by Django 3.1.1 on 2020-10-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20201030_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='pub_date',
        ),
    ]
