# Generated by Django 3.1.1 on 2020-10-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20201031_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, help_text='Нужно для того чтобы два модуля были взаимоисключаемые,слово должно быть без пробелов', max_length=250, null=True, verbose_name='Уникальное слово'),
        ),
    ]
