# Generated by Django 3.1.1 on 2020-11-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20201031_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='module',
            field=models.TextField(blank=True, null=True, verbose_name='Модули'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, help_text='Нужно для того чтобы два модуля были взаимоисключаемые,слово должно быть без пробелов и на английском', max_length=250, null=True, verbose_name='Уникальное слово'),
        ),
    ]
