# Generated by Django 3.1.1 on 2020-11-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20201102_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='module',
            field=models.TextField(blank=True, null=True, verbose_name='Модули'),
        ),
    ]
