# Generated by Django 3.1.1 on 2020-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_orderproduct_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_trade',
            field=models.BooleanField(default=False, verbose_name='tradeIn'),
        ),
    ]
