# Generated by Django 3.1.1 on 2020-11-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20201110_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_category',
            field=models.CharField(blank=True, choices=[('apple-tv', 'Apple TV '), ('cables', 'Кабели'), ('adapters', 'Переходники'), ('protective-glass', 'Защитные стекла'), ('stylus', 'Стилусы'), ('keyboards-and-mouse', 'Клавиатуры и мышки'), ('charging-device', 'Зарядные устройства'), ('headphones-and-speakers', 'Наушники и колонки'), ('cases-and-bags', 'Чехлы и сумки'), ('drones', 'Дроны'), ('stabilizers', 'Стабилизаторы'), ('camera', 'Камеры'), ('garmin', 'Garmin'), ('vr-glasses', 'VR  очки'), ('graphic-tablets', 'Графические планшеты'), ('another', 'Разное')], max_length=30, null=True, verbose_name='Подкатегория'),
        ),
    ]
