# Generated by Django 3.1.1 on 2020-11-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20201127_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_category',
            field=models.CharField(blank=True, choices=[('apple-tv', 'Apple TV '), ('cables', 'Кабели'), ('adapters', 'Переходники'), ('protective-glass', 'Защитные стекла'), ('stylus', 'Стилусы'), ('keyboards-and-mouse', 'Клавиатуры и мышки'), ('charging-device', 'Зарядные устройства'), ('headphones-and-speakers', 'Наушники и колонки'), ('cases-and-bags', 'Чехлы и сумки'), ('drones', 'Дроны'), ('stabilizers', 'Стабилизаторы'), ('camera', 'Камеры'), ('garmin', 'Garmin'), ('vr-glasses', 'VR  очки'), ('graphic-tablets', 'Графические планшеты'), ('another', 'Разное'), ('mac-16', 'MacBook Pro 16'), ('mac-13', 'MacBook Pro 13'), ('mac-13-air', 'MacBook Air 13'), ('mac-12', 'MacBook Retina 12'), ('mac-mini', 'Mac mini'), ('mac-pro', 'Mac Pro')], max_length=30, null=True, verbose_name='Подкатегория'),
        ),
    ]
