# Generated by Django 3.1.1 on 2020-12-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20201130_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна'),
        ),
    ]
