# Generated by Django 3.1.1 on 2020-12-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('iphone', 'iPhone '), ('macBook', 'MacBook '), ('iPad', 'iPad'), ('iMac', 'iMac'), ('apple-watch', 'Apple Watch'), ('gadgets', 'Гаджеты'), ('airpods', 'AirPods'), ('accessory', 'Аксеcсуары'), ('another', 'Разное')], max_length=20, null=True, verbose_name='Категория'),
        ),
    ]
