# Generated by Django 3.1.1 on 2020-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20201218_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
    ]
