# Generated by Django 3.1.1 on 2021-07-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_productspecification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='УКТ'),
        ),
    ]
