# Generated by Django 3.1.1 on 2021-07-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_auto_20210729_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Сихронизировать'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Найден ли?'),
        ),
    ]
