# Generated by Django 3.1.1 on 2021-07-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20210729_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Сихронизировать'),
        ),
    ]
