# Generated by Django 3.1.1 on 2021-08-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20210729_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Найден'),
        ),
    ]
