# Generated by Django 3.1.1 on 2021-08-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20210803_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='УКТ'),
        ),
    ]
