# Generated by Django 3.1.1 on 2021-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20210809_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена за штуку в $'),
        ),
    ]
