# Generated by Django 3.1.1 on 2021-09-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20210812_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='need_pay',
            field=models.FloatField(blank=True, null=True, verbose_name='Нужно оплатить'),
        ),
    ]
