# Generated by Django 3.1.1 on 2021-09-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_auto_20210919_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
        ),
        migrations.AddField(
            model_name='productspecification',
            name='caseSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caseSize', to='products.casesize', verbose_name='Размер корпуса'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='connectivity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectivity', to='products.connectivity', verbose_name='Раскладка клавиатуры'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu', to='products.cpu', verbose_name='Раскладка клавиатуры'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edition', to='products.edition', verbose_name='Раскладка клавиатуры'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='keyboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyboard', to='products.keyboard', verbose_name='Раскладка клавиатуры'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern', to='products.pattern', verbose_name='Раскладка клавиатуры'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram', to='products.ram', verbose_name='Раскладка клавиатуры'),
        ),
    ]
