# Generated by Django 3.1.1 on 2021-09-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20210924_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='images',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='images',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='Изображении', to='products.Image'),
        ),
    ]
