# Generated by Django 3.1.1 on 2021-09-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_auto_20210924_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='images',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='images',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='', verbose_name='Изображении'),
        ),
    ]
