# Generated by Django 3.1.1 on 2021-09-26 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_auto_20210925_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='images',
        ),
        migrations.AlterField(
            model_name='image',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.productspecification'),
        ),
    ]
