# Generated by Django 3.1.1 on 2021-09-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_auto_20210926_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='image',
            new_name='img',
        ),
    ]
