# Generated by Django 3.1.1 on 2021-10-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_auto_20211003_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='caseSize',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер корпуса'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='connectivity',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Возможности подключения'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cpu',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='edition',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Edition'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='keyboard',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Раскладка клавиатуры'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='pattern',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='ram',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_order', to='products.productspecification'),
        ),
    ]
