# Generated by Django 3.1.1 on 2021-10-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_auto_20211003_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='module',
        ),
    ]
