# Generated by Django 3.1.1 on 2021-10-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_auto_20211003_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='second_category',
            new_name='additional_category',
        ),
    ]
