# Generated by Django 3.1.1 on 2021-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_auto_20211003_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
    ]
